version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/access-analyzer
  - /modules/cloudtrail-event-data-store
  - /modules/cloudtrail-trail
  - /modules/config-managed-rule
  - /modules/config-recorder
  - /modules/macie-account
  schedule:
    interval: weekly
