# Modules
- color: "fbca04"
  description: "This issue or pull request is related to access-analyzer module."
  name: ":floppy_disk: access-analyzer"
- color: "fbca04"
  description: "This issue or pull request is related to cloudtrail-event-data-store module."
  name: ":floppy_disk: cloudtrail-event-data-store"
- color: "fbca04"
  description: "This issue or pull request is related to cloudtrail-trail module."
  name: ":floppy_disk: cloudtrail-trail"
- color: "fbca04"
  description: "This issue or pull request is related to config-managed-rule module."
  name: ":floppy_disk: config-managed-rule"
- color: "fbca04"
  description: "This issue or pull request is related to config-recorder module."
  name: ":floppy_disk: config-recorder"
- color: "fbca04"
  description: "This issue or pull request is related to macie-account module."
  name: ":floppy_disk: macie-account"
- color: "fbca04"
  description: "This issue or pull request is related to macie-custom-data-identifier module."
  name: ":floppy_disk: macie-custom-data-identifier"
